name: 'Setup Hurl'
description: 'Setup Hurl and add it to the PATH'
author: 'Niklas Mollenhauer'
inputs:
  hurl-version:
    description: 'The hurl version to download (if necessary) and use. Supports semver spec and ranges.'
runs:
  using: composite
  steps:
  - run: npm i -g "@orangeopensource/hurl@${{ inputs.hurl-version }}"
    shell: bash
